export const TYPES = {
    LOGIN : "LOGIN",
    LOGOUT : "LOGOUT",
    GET_PRODUCT_LOAD : "GET_PRODUCT_LOAD",
    GET_PRODUCT_SUCCEED : "GET_PRODUCT_SUCCEED",
    GET_PRODUCT_FAIL : "GET_PRODUCT_FAIL",
    
};